function vol = generate_volume(k, sigma, T)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
vol = exp(1 * 1i*k'*T(:,1)) .* exp(-0.7 * pi^2/sigma*sum(k.*k)).' + ...
      exp(1 * 1i*k'*T(:,2)) .* exp(-0.5 * pi^2/sigma*sum(k.*k)).' + ...
      exp(1 * 1i*k'*T(:,3)) .* exp(-0.4 * pi^2/sigma*sum(k.*k)).' + ...
      exp(1 * 1i*k'*T(:,4)) .* exp(-0.6 * pi^2/sigma*sum(k.*k)).' + ...
      exp(1 * 1i*k'*T(:,5)) .* exp(-0.8 * pi^2/sigma*sum(k.*k)).' ;
end